spring.application.name=${SPRING_APPLICATION_NAME:server}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/manga_db}
